/*
SOMEBODY ONCE TOLD ME THE WORLD IS GONNA ROLL ME
I AINT THE SHARPEST TOOL IN SHED
SHE WAS LOOKING KIND OF DUMB WITH HER FINGER AND HER THUMB IN THE SHAPE OF AN 'L' ON HER FOREHEAD
WELL THE YEARS START COMING AND THEY DONT STOP COMING
FED TO THE RULES SO I HIT THE GROUND RUNNING
DIDNT MAKE SENSE NOT TO LIVE FOR FUN
YOUR BRAIN GETS SMART BUT YOUR HEAD GETS DUMB
SO MUCH TO DO SO MUCH TO SEE SO WHATS WRONG WITH TAKING THE BACK STREETS
YOU'LL NEVER KNOW IF YOU DONT KNOW YOULL NEVER SHINE IF YOU DONT GLOW
HEY NOW YOURE AN ALL STAR GET YOUR GAME ON GO PLAY
HEY NOW YOURE A ROCKSTAR GET YOUR SHOW ON GET PAID
ALL THAT GLITTERS IS GOLD ONLY SHOOTING STARS BREAK THE MOLD
ITS A COOL PLACE AND THEY SAY IT GETS COLDER
YOURE BUNDLED UP NOW BUT WAIT TILL YOU GET OLDER
BUT THE METEOR MEN BEG TO DIFFER JUDGING BY THE HOLE IN THE SATTELITE PICTURE
THE ICE WE SKATE IS GETTING PRETTY THIN
THE WATERS QUITE WARM SO YOU MIGHT AS WELL SWIM
MY WORLDS ON FIRE HOW ABOUT YOURS
THATS THE WAY I LIKE IT AND ILL NEVER GET BORED
HEY NOW YOURE AN ALLSTAR GET YOUR GAME ON GO PLAY
HEY NOW YOURE A ROCKSTAR GET THE SHOW ON GET PAID
ALL THAT GLITTERS IS GOLD ONLY SHOOTING STARS BREAK THE MOLD

*/